// GENERATED by @edgedb/generate v0.5.3

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
export type $CharactersλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "description": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "title": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "<characters[is Stories]": $.LinkDesc<$Stories, $.Cardinality.Many, {}, false, false,  false, false>;
  "<characters": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Characters = $.ObjectType<"default::Characters", $CharactersλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $Characters = $.makeType<$Characters>(_.spec, "f25f4b8c-15db-11ef-9509-c90c5f34a0b5", _.syntax.literal);

const Characters: $.$expr_PathNode<$.TypeSet<$Characters, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Characters, $.Cardinality.Many), null);

export type $StoriesλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "characters": $.LinkDesc<$Characters, $.Cardinality.Many, {}, false, false,  false, false>;
  "storypoints": $.LinkDesc<$Storypoints, $.Cardinality.Many, {}, false, false,  false, false>;
  "title": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
}>;
type $Stories = $.ObjectType<"default::Stories", $StoriesλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $Stories = $.makeType<$Stories>(_.spec, "f261e4db-15db-11ef-b019-239e9e63328b", _.syntax.literal);

const Stories: $.$expr_PathNode<$.TypeSet<$Stories, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Stories, $.Cardinality.Many), null);

export type $StorypointsλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "description": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "title": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "<storypoints[is Stories]": $.LinkDesc<$Stories, $.Cardinality.Many, {}, false, false,  false, false>;
  "<storypoints": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Storypoints = $.ObjectType<"default::Storypoints", $StorypointsλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $Storypoints = $.makeType<$Storypoints>(_.spec, "f2609813-15db-11ef-97f5-03256d1ff6f4", _.syntax.literal);

const Storypoints: $.$expr_PathNode<$.TypeSet<$Storypoints, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Storypoints, $.Cardinality.Many), null);

export type $UsersλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "email": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "fname": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "img": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "lname": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "password": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "username": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
}>;
type $Users = $.ObjectType<"default::Users", $UsersλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $Users = $.makeType<$Users>(_.spec, "f263986d-15db-11ef-9fe4-f15ef031520b", _.syntax.literal);

const Users: $.$expr_PathNode<$.TypeSet<$Users, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Users, $.Cardinality.Many), null);



export { $Characters, Characters, $Stories, Stories, $Storypoints, Storypoints, $Users, Users };

type __defaultExports = {
  "Characters": typeof Characters;
  "Stories": typeof Stories;
  "Storypoints": typeof Storypoints;
  "Users": typeof Users
};
const __defaultExports: __defaultExports = {
  "Characters": Characters,
  "Stories": Stories,
  "Storypoints": Storypoints,
  "Users": Users
};
export default __defaultExports;
